
local objects = {
        {
          id = 5,
          name = "Coin",
          type = "",
          shape = "rectangle",
          x = 159.667,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 54,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "Coin",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 224.667,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 54,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "Coin",
          type = "",
          shape = "rectangle",
          x = 191.667,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 54,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "Coin",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 128.333,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 54,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "Coin",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 271.5,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 54,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "Coin",
          type = "",
          shape = "rectangle",
          x = 336,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 54,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "Gem",
          type = "",
          shape = "rectangle",
          x = 655.5,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 59,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "Gem",
          type = "",
          shape = "rectangle",
          x = 33,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 59,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "Gem",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 47.5,
          width = 16,
          height = 16,
          rotation = 0,
          gid = 59,
          visible = true,
          properties = {}
        }
      }
return objects